name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          config_timezone: America/Sao_Paulo
          extras_css: |
            {{ lookup('file', 'custom_metrics.css') }}
          base_indepth: yes
          config_order: base.header, base_indepth, metadata, header, activity, community, repositories, isocalendar, languages, people
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, scala, c, c++, python, ejs
          plugin_languages_details: lines, bytes-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 2
          plugin_isocalendar_duration: half-year
          plugin_people: yes
          plugin_people_types: followers


      - name: Media
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: media.svg
          token: NOT_NEEDED
          base: ""
          config_timezone: America/Sao_Paulo
          extras_css: |
            <style>
              body {
                  background: linear-gradient(to right, #8e54e9, #4776e6);
                  font-family: Arial, sans-serif;
                  margin: 0;
                  padding: 0;
                  display: flex;
                  justify-content: center;
                  align-items: center;
                  height: 100vh;
              }
              
              .container {
                  background: rgba(255, 255, 255, 0.15);
                  border-radius: 15px;
                  padding: 20px;
                  backdrop-filter: blur(10px);
                  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1), 0 1px 3px rgba(0, 0, 0, 0.08);
              }
              
              h2 {
                  color: #32a852;
                  text-align: center;
                  margin-bottom: 20px;
              }
              
              .metric-container {
                  display: flex;
                  flex-wrap: wrap;
                  justify-content: space-around;
              }
              
              .metric {
                  width: 45%;
                  padding: 20px;
                  margin: 10px;
                  border-radius: 10px;
                  background: rgba(255, 255, 255, 0.2);
                  backdrop-filter: blur(5px);
                  box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
              }
              
              h3 {
                  color: #fff;
                  font-size: 18px;
                  margin-bottom: 10px;
              }
              
              p {
                  color: #fff;
                  font-size: 14px;
                  margin-bottom: 10px;
              }
            </style>
          config_order: anilist, music, steam
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites,characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 20
          plugin_anilist_user: RecNove
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_user: RecNove
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198066083877"
          plugin_steam_sections: player, most-played
