name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 16 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: 🦑 General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: general.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          config_timezone: America/Sao_Paulo
          extras_css: |
            h1, h2, h3, h4, h5, h6, p, span, label, a { 
              color: #8100f7;
            }
            b{
              color: #76F700;
            }
          base_indepth: yes
          config_order: base.header, base_indepth, metadata, header, activity, community, repositories, isocalendar, languages, people
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, scala, c, c++, python, ejs, procfile
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_people: yes
          plugin_people_types: followers


      - name: Media
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: media.svg
          token: NOT_NEEDED
          base: ""
          config_timezone: America/Sao_Paulo
          extras_css: |
            h1, h2, h3, h4, h5, h6, p, span, label, a { 
              color: #8100f7;
            }
            b{
              color: #76F700;
            }
          config_order: anilist, music, steam
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites,characters
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_user: RecNove
          plugin_music_token: ${{ secrets.LASTFM_TOKEN }}
          plugin_music: yes
          plugin_music_provider: lastfm
          plugin_music_user: RecNove
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam: yes
          plugin_steam_user: "76561198066083877"
          plugin_steam_sections: player, most-played
